name: acueductoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  geolocator: ^13.0.1
  http: ^1.2.2
  latlong2: ^0.9.1
  flutter_map_heatmap: ^0.0.7
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
